# GENERATED by tools/gen_palette.py from art/palette/palette.json. Do not edit.
class_name Palette
extends RefCounted

const GRID := Vector2i(8, 4)

## Palette cell (column, row) for every named colour.
const CELLS: Dictionary[StringName, Vector2i] = {
	&"grass_light": Vector2i(0, 0),
	&"grass_mid": Vector2i(1, 0),
	&"leaf_dark": Vector2i(2, 0),
	&"leaf_teal": Vector2i(3, 0),
	&"moss": Vector2i(4, 0),
	&"bark_light": Vector2i(5, 0),
	&"bark_mid": Vector2i(6, 0),
	&"bark_dark": Vector2i(7, 0),
	&"wood_plank": Vector2i(0, 1),
	&"wood_warm": Vector2i(1, 1),
	&"roof_red": Vector2i(2, 1),
	&"roof_blue": Vector2i(3, 1),
	&"roof_teal": Vector2i(4, 1),
	&"thatch": Vector2i(5, 1),
	&"stone_light": Vector2i(6, 1),
	&"stone_dark": Vector2i(7, 1),
	&"water_light": Vector2i(0, 2),
	&"water_mid": Vector2i(1, 2),
	&"water_deep": Vector2i(2, 2),
	&"foam": Vector2i(3, 2),
	&"sky_top": Vector2i(4, 2),
	&"portal_magenta": Vector2i(5, 2),
	&"portal_teal": Vector2i(6, 2),
	&"gold": Vector2i(7, 2),
	&"skin_light": Vector2i(0, 3),
	&"skin_mid": Vector2i(1, 3),
	&"skin_dark": Vector2i(2, 3),
	&"tunic_blue": Vector2i(3, 3),
	&"cloth_cream": Vector2i(4, 3),
	&"slime_green": Vector2i(5, 3),
	&"slime_blue": Vector2i(6, 3),
	&"gloop_pink": Vector2i(7, 3),
}

## The same colours as Color values, for UI, particles and lights.
const COLORS: Dictionary[StringName, Color] = {
	&"grass_light": Color("#A9D65A"),
	&"grass_mid": Color("#82BD45"),
	&"leaf_dark": Color("#4F8A35"),
	&"leaf_teal": Color("#69A85A"),
	&"moss": Color("#BFCB4E"),
	&"bark_light": Color("#C98A52"),
	&"bark_mid": Color("#9C6038"),
	&"bark_dark": Color("#6E3F25"),
	&"wood_plank": Color("#E6AE6E"),
	&"wood_warm": Color("#CF8442"),
	&"roof_red": Color("#E8664A"),
	&"roof_blue": Color("#5B86D0"),
	&"roof_teal": Color("#4FB8A4"),
	&"thatch": Color("#F0CB70"),
	&"stone_light": Color("#DCCBB2"),
	&"stone_dark": Color("#A38F7C"),
	&"water_light": Color("#7FE0F0"),
	&"water_mid": Color("#39A9DB"),
	&"water_deep": Color("#2A6FB0"),
	&"foam": Color("#F4FBFF"),
	&"sky_top": Color("#7CC8F2"),
	&"portal_magenta": Color("#E05AD6"),
	&"portal_teal": Color("#4DF0D2"),
	&"gold": Color("#FFC83D"),
	&"skin_light": Color("#FFD9B8"),
	&"skin_mid": Color("#E0A37A"),
	&"skin_dark": Color("#9C6644"),
	&"tunic_blue": Color("#3D7BE0"),
	&"cloth_cream": Color("#F5EBD3"),
	&"slime_green": Color("#63E06B"),
	&"slime_blue": Color("#4FB7FF"),
	&"gloop_pink": Color("#F2709C"),
}

const INK := Color("#3A2633")
const SHADOW_TINT := Color("#8C6A8C")
const FOG := Color("#F6E4CC")


static func cell(color_name: StringName) -> Vector2i:
	assert(CELLS.has(color_name), "Unknown palette colour: %s" % color_name)
	return CELLS.get(color_name, Vector2i.ZERO)


static func color(color_name: StringName) -> Color:
	assert(COLORS.has(color_name), "Unknown palette colour: %s" % color_name)
	return COLORS.get(color_name, Color.MAGENTA)
