#!/usr/bin/env python3
"""palette.json -> game/assets/textures/palette.png (128x64, 16px cells) + game/scripts/core/palette.gd.

The JSON is the only source of colours (plan §10.2). Re-run after editing it: `make palette`.
"""
import json, pathlib, struct, zlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
spec = json.loads((ROOT / "art/palette/palette.json").read_text())
cols, rows = spec["grid"]
px = spec["cell_px"]

def hex_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))

grid = [[hex_rgb(c[1]) for c in row["colors"]] for row in spec["rows"]]
w, h = cols * px, rows * px
raw = bytearray()
for y in range(h):
    raw.append(0)
    for x in range(w):
        raw.extend(grid[y // px][x // px])

def chunk(tag, data):
    return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0))
png += chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b"")
out_png = ROOT / "game/assets/textures/palette.png"
out_png.parent.mkdir(parents=True, exist_ok=True)
out_png.write_bytes(png)

lines = [
    "# GENERATED by tools/gen_palette.py from art/palette/palette.json. Do not edit.",
    "class_name Palette",
    "extends RefCounted",
    "",
    "const GRID := Vector2i(%d, %d)" % (cols, rows),
    "",
    "## Palette cell (column, row) for every named colour.",
    "const CELLS: Dictionary[StringName, Vector2i] = {",
]
for r, row in enumerate(spec["rows"]):
    for c, (name, _hex) in enumerate(row["colors"]):
        lines.append('\t&"%s": Vector2i(%d, %d),' % (name, c, r))
lines += ["}", "", "## The same colours as Color values, for UI, particles and lights.", "const COLORS: Dictionary[StringName, Color] = {"]
for row in spec["rows"]:
    for name, hx in row["colors"]:
        lines.append('\t&"%s": Color("%s"),' % (name, hx))
lines += ["}", ""]
for name, hx in spec["shader_only"].items():
    lines.append('const %s := Color("%s")' % (name.upper(), hx))
lines += [
    "",
    "",
    "static func cell(color_name: StringName) -> Vector2i:",
    "\tassert(CELLS.has(color_name), \"Unknown palette colour: %s\" % color_name)",
    "\treturn CELLS.get(color_name, Vector2i.ZERO)",
    "",
    "",
    "static func color(color_name: StringName) -> Color:",
    "\tassert(COLORS.has(color_name), \"Unknown palette colour: %s\" % color_name)",
    "\treturn COLORS.get(color_name, Color.MAGENTA)",
    "",
]
(ROOT / "game/scripts/core/palette.gd").write_text("\n".join(lines))
print("palette: wrote", out_png.relative_to(ROOT), "and game/scripts/core/palette.gd")
